package com.example.userservice.service;

import com.example.userservice.dto.UserRegistrationRequest;
import com.example.userservice.exception.ValidationException;
import com.example.userservice.model.User;
import com.example.userservice.repository.UserRepository;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Service class responsible for handling user-related business logic,
 * particularly user registration.
 */
public class UserService {
    private final UserRepository userRepository;

    // Simple email regex pattern (can be more robust for production, e.g., using Apache Commons Validator)
    private static final Pattern EMAIL_PATTERN =
            Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");

    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    /**
     * Registers a new user based on the provided registration request.
     * Performs various validation checks (input format, uniqueness) and then persists the user
     * if all checks pass.
     *
     * @param request The user registration request DTO containing username, password, and email.
     * @return The newly registered User object, including its generated ID and hashed password.
     * @throws ValidationException If any validation check fails, containing details about the errors.
     */
    public User registerUser(UserRegistrationRequest request) throws ValidationException {
        Map<String, String> errors = new HashMap<>();

        // 1. Basic Input Validation (null/empty, format, length)
        validateUsername(request.getUsername(), errors);
        validatePassword(request.getPassword(), errors);
        validateEmail(request.getEmail(), errors);

        // If basic input validation fails, throw exception immediately
        // This prevents unnecessary database lookups for invalid input
        if (!errors.isEmpty()) {
            throw new ValidationException("User registration input validation failed.", errors);
        }

        // 2. Business Logic Validation (Uniqueness checks)
        // Check if username already exists
        userRepository.findByUsername(request.getUsername()).ifPresent(u ->
            errors.put("username", "Username '" + request.getUsername() + "' is already taken.")
        );

        // Check if email already exists
        userRepository.findByEmail(request.getEmail()).ifPresent(u ->
            errors.put("email", "Email '" + request.getEmail() + "' is already registered.")
        );

        // If business logic validation (uniqueness) fails, throw exception
        if (!errors.isEmpty()) {
            throw new ValidationException("User registration uniqueness validation failed.", errors);
        }

        // 3. If all checks pass, proceed to register the user
        String hashedPassword = hashPassword(request.getPassword());

        // Create a new User entity. The ID will be generated by the repository (or database).
        // Passing null for ID tells the InMemoryUserRepositoryImpl to generate a new one.
        User newUser = new User(null, request.getUsername(), request.getEmail(), hashedPassword);

        // Save the user using the repository
        return userRepository.save(newUser);
    }

    /**
     * Validates the username field.
     * @param username The username string.
     * @param errors A map to accumulate validation errors.
     */
    private void validateUsername(String username, Map<String, String> errors) {
        if (username == null || username.trim().isEmpty()) {
            errors.put("username", "Username cannot be empty.");
        } else if (username.length() < 4 || username.length() > 20) {
            errors.put("username", "Username must be between 4 and 20 characters long.");
        } else if (!username.matches("^[a-zA-Z0-9_.-]+$")) { // Allows letters, numbers, underscore, dot, hyphen
            errors.put("username", "Username can only contain letters, numbers, underscores, dots, and hyphens.");
        }
    }

    /**
     * Validates the password field.
     * @param password The password string (plain text from request).
     * @param errors A map to accumulate validation errors.
     */
    private void validatePassword(String password, Map<String, String> errors) {
        if (password == null || password.isEmpty()) {
            errors.put("password", "Password cannot be empty.");
        } else if (password.length() < 8) {
            errors.put("password", "Password must be at least 8 characters long.");
        }
        // Additional password policy checks (e.g., requires uppercase, lowercase, digit, special char)
        // could be added here for stronger security.
        // For example:
        // if (!password.matches(".*[A-Z].*")) { errors.put("password", "Password must contain at least one uppercase letter."); }
        // etc.
    }

    /**
     * Validates the email field.
     * @param email The email string.
     * @param errors A map to accumulate validation errors.
     */
    private void validateEmail(String email, Map<String, String> errors) {
        if (email == null || email.trim().isEmpty()) {
            errors.put("email", "Email cannot be empty.");
        } else if (!EMAIL_PATTERN.matcher(email).matches()) {
            errors.put("email", "Invalid email format.");
        }
    }

    /**
     * Placeholder for password hashing logic.
     * In a real application, this method should use a strong, one-way hashing algorithm
     * like BCrypt, SCrypt, or Argon2, provided by a security library (e.g., Spring Security's PasswordEncoder,
     * Apache Shiro, or similar).
     * <p>
     * DO NOT store plain text passwords in a production environment.
     * </p>
     * @param password The plain text password.
     * @return The hashed password string.
     */
    private String hashPassword(String password) {
        // For demonstration purposes, we'll just prefix it to indicate it's "hashed".
        // In a production system, replace this with a proper hashing library.
        // Example with a placeholder prefix:
        return "{bcrypt}" + password; // Simulate a hashed password, e.g., using BCrypt algorithm
        // return new BCryptPasswordEncoder().encode(password); // If using Spring Security
    }
}
